/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica5;

import java.awt.Color;
import java.util.logging.Level;
import java.util.Random;

/**
 *
 * @author wonfix
 */
public class Generador extends java.awt.Frame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Generador.class.getName());

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        
        int ancho = 900, alto = 600;
        
        Generador G = new Generador();
        G.setTitle("Parking: 'Plaza Central'");
        G.setSize(ancho, alto);
        G.setLocation(100, 100);
        
        CanvasGenerador cv = new CanvasGenerador(ancho, alto);
        G.add(cv);
        G.setVisible(true);
        
        
        Thread[] vehiculos = new Thread[30];
        Combustion c;
        Parking pk = new Parking(cv);
        
        Random r = new Random();
        r.setSeed(System.currentTimeMillis());
        
        try {
            System.out.println("Abre el Parking: 'Plaza Central' ");
            for(int i = 0; i < 30; i++){
                if(r.nextInt(100) < 50){
                    vehiculos[i] = new Electrico(pk, i);
                    //Comineza los hilos creado
                    vehiculos[i].start();
                } else {
                    c = new Combustion(pk,i); 
                    vehiculos[i] = new Thread(c);
                    vehiculos[i].start();
                }
                Thread.sleep((r.nextInt(2) + 1) * 10);
            }
            
            for (int i = 0; i < 30; i++) {
                vehiculos[i].join();
            }
        } catch (InterruptedException ex){
            System.out.println("Ha dado algun error ....");
        }
        System.out.println("Cierra el Parking: 'Plaza Central' ");
        
        //java.awt.EventQueue.invokeLater(() -> new Generador().setVisible(true));
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
