/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package clase3_pedro;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class FrameP3 extends java.awt.Frame {

    /**
     * Creates new form FrameP3
     */
    public FrameP3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        
        int ancho = 600, alto = 400;
        FrameP3 F = new FrameP3();
        F.setTitle("Practica 3 de PCD");
        //LE pone el tamaño x, y(ancho y alto )
        F.setSize(ancho, alto);
        F.setBackground(Color.yellow);
        //siempre se empieza de arriba a la izquierda de la pantalla que sera la 0,0
        F.setLocation(100, 100);
        
        
        MiCanvas cv = new MiCanvas(ancho, alto);
        F.add(cv);
        
        F.setVisible(true);
        
        Datos d = new Datos(cv);
        
        d.incrementa(0);
        d.incrementa(1);
        
        Sumador h1 = new Sumador(d, 0);
        Sumador h2 = new Sumador(d, 1);
        Sumador h3 = new Sumador(d, 0);
        
        h1.start();
        h2.start();
        h3.start();
        
        h1.join();
        h2.join();
        h3.join();
        int[] val = d.getContadores();
        System.out.println("Los contadores valen: " + "{"+ val[0] + " ," + val[1] + "}");
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
