/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3_prueba;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class EjemploAPP extends java.awt.Frame {

    /**
     * Creates new form EjemploAPP
     */
    public EjemploAPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonsalir = new java.awt.Button();

        setPreferredSize(new java.awt.Dimension(600, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        botonsalir.setActionCommand("botonsalir");
        botonsalir.setBackground(java.awt.Color.pink);
        botonsalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonsalir.setLabel("Salir");
        botonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalirActionPerformed(evt);
            }
        });
        add(botonsalir, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void botonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
       
        final int ancho=600, alto=400;
        EjemploAPP f = new EjemploAPP();
        Lienzo cv = new Lienzo(ancho,alto);
        
        f.setSize(ancho, alto);
        f.setBackground(Color.GRAY);
        f.setTitle("Ejemplo Frame Practica 3");
        f.add(cv);
        f.setVisible(true);
        
        
        Recurso r = new Recurso(cv);
        r.incrementa(0);
        r.verContadores();
        
        /*Hilo[] loshilos = new Hilo[5];
        for (int i = 0; i < 5; i++) {
            loshilos[i] = new Hilo(r,0);  
        }*/
        
        Hilo h1 = new Hilo(r,0);
        Hilo h2 = new Hilo(r,1);
        Hilo h3 = new Hilo(r,1);
        
        h1.start();
        h2.start();
        h3.start();
        
        h1.join();
        h2.join();
        h3.join();
        
        r.verContadores();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Button botonsalir;
    // End of variables declaration//GEN-END:variables
}
