/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica;

import java.awt.Color;

/**
 *
 * @author Pablo
 */
public class PilaFrame extends java.awt.Frame {

    /**
     * Creates new form PilaFrame
     */
    public PilaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(800, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException, Exception {
        final int ancho = 900, alto = 600;
        PilaFrame pF = new PilaFrame();
        CanvasPila cv = new CanvasPila(ancho, alto, 7);

        pF.setSize(ancho, alto);
        pF.setBackground(Color.GRAY);
        pF.setTitle("Practica 3 Pila");
        pF.add(cv);
        pF.setVisible(true);

        PilaLenta p = new PilaLenta(7, cv);

        Productor h1 = new Productor(p, 0);
        Productor h2 = new Productor(p, 1);
        Productor h3 = new Productor(p, 2);
        Productor h4 = new Productor(p, 3);

        Consumidor c1 = new Consumidor(p);
        Thread h5 = new Thread(c1);

        h1.start();
        h2.start();
        h3.start();
        h4.start();
        h5.start();

        h5.join();

        Thread.sleep(1000);
        synchronized (p) {
            p.notifyAll();
        }

        h1.join();
        h2.join();
        h3.join();
        h4.join();

        System.out.println(" ");
        System.out.println("Numero de elementos de la Pila : " + p.GetNum());
        System.out.println("");

        System.out.println("HILOS FINALIZADOS!!!!!");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
